In [9]:
from torch.utils.tensorboard import SummaryWriter

In [2]:
pip install tensorboard

     ---------------------------------------- 0.0/5.6 MB ? eta -:--:--
      --------------------------------------- 0.1/5.6 MB 3.3 MB/s eta 0:00:02
     --- ------------------------------------ 0.5/5.6 MB 6.0 MB/s eta 0:00:01
     ------ --------------------------------- 0.9/5.6 MB 7.3 MB/s eta 0:00:01
     ---------- ----------------------------- 1.5/5.6 MB 8.4 MB/s eta 0:00:01
     -------------- ------------------------- 2.0/5.6 MB 9.1 MB/s eta 0:00:01
     ------------------ --------------------- 2.5/5.6 MB 9.5 MB/s eta 0:00:01
     ---------------------- ----------------- 3.1/5.6 MB 9.8 MB/s eta 0:00:01
     ------------------------- -------------- 3.6/5.6 MB 10.0 MB/s eta 0:00:01
     ----------------------------- ---------- 4.1/5.6 MB 10.1 MB/s eta 0:00:01
     --------------------------------- ------ 4.6/5.6 MB 10.2 MB/s eta 0:00:01
     ------------------------------------- -- 5.2/5.6 MB 10.3 MB/s eta 0:00:01
     ---------------------------------------  5.6/5.6 MB 10.5 MB/s 

Show Graph using tensorboard
add_scalar()

In [10]:
writer = SummaryWriter("logs")

# writer.add_image()
# writer.add_scalar()
for i in range(100):
    writer.add_scalar("y=2x", scalar_value=2*i, global_step=i)

writer.close()

Show images using tensorboard
add_image()

In [4]:
import cv2
import numpy as np
from PIL import Image

In [21]:
image_path = r"C:\Users\tsx10\PythonProjectsJupyter\Python_Vertiefen\Pytorch\Dataset\Data\train\ants_image\0013035.jpg"
image_array = np.array(Image.open(image_path))
image_array

array([[[ 80, 151, 233],
        [ 80, 151, 233],
        [ 80, 151, 233],
        ...,
        [ 81, 152, 234],
        [ 79, 150, 232],
        [ 76, 147, 229]],

       [[ 81, 152, 234],
        [ 81, 152, 234],
        [ 81, 152, 234],
        ...,
        [ 81, 152, 234],
        [ 79, 150, 232],
        [ 76, 147, 229]],

       [[ 82, 153, 235],
        [ 82, 153, 235],
        [ 82, 153, 235],
        ...,
        [ 80, 151, 233],
        [ 79, 150, 232],
        [ 77, 148, 230]],

       ...,

       [[ 87, 160, 237],
        [ 87, 160, 237],
        [ 86, 159, 236],
        ...,
        [ 44,  92, 141],
        [ 95, 158, 235],
        [ 90, 157, 228]],

       [[ 87, 160, 237],
        [ 87, 160, 237],
        [ 86, 159, 236],
        ...,
        [ 84, 147, 226],
        [ 90, 160, 255],
        [ 84, 152, 233]],

       [[ 87, 160, 237],
        [ 87, 160, 237],
        [ 86, 159, 236],
        ...,
        [ 79, 160, 242],
        [ 78, 159, 250],
        [ 84, 161, 233]]

Dataformat define the dataform like PIL and Opencv have different input channals

In [24]:
writer.add_image(tag="test", img_tensor=image_array, global_step=1, dataformats="HWC")

image preporcessing using transforms

transforms.ToTensor

In [2]:
from torchvision import transforms

In [27]:

image_path = r"C:\Users\tsx10\PythonProjectsJupyter\Python_Vertiefen\Pytorch\Dataset\Data\train\ants_image\0013035.jpg"
img = Image.open(image_path)
tensor_trans = transforms.ToTensor() # return ToTensor class 
tensor_img = tensor_trans(img) # Convert a PIL Image or ndarray to tensor and scale the values accordingly
tensor_img

tensor([[[0.3137, 0.3137, 0.3137,  ..., 0.3176, 0.3098, 0.2980],
         [0.3176, 0.3176, 0.3176,  ..., 0.3176, 0.3098, 0.2980],
         [0.3216, 0.3216, 0.3216,  ..., 0.3137, 0.3098, 0.3020],
         ...,
         [0.3412, 0.3412, 0.3373,  ..., 0.1725, 0.3725, 0.3529],
         [0.3412, 0.3412, 0.3373,  ..., 0.3294, 0.3529, 0.3294],
         [0.3412, 0.3412, 0.3373,  ..., 0.3098, 0.3059, 0.3294]],

        [[0.5922, 0.5922, 0.5922,  ..., 0.5961, 0.5882, 0.5765],
         [0.5961, 0.5961, 0.5961,  ..., 0.5961, 0.5882, 0.5765],
         [0.6000, 0.6000, 0.6000,  ..., 0.5922, 0.5882, 0.5804],
         ...,
         [0.6275, 0.6275, 0.6235,  ..., 0.3608, 0.6196, 0.6157],
         [0.6275, 0.6275, 0.6235,  ..., 0.5765, 0.6275, 0.5961],
         [0.6275, 0.6275, 0.6235,  ..., 0.6275, 0.6235, 0.6314]],

        [[0.9137, 0.9137, 0.9137,  ..., 0.9176, 0.9098, 0.8980],
         [0.9176, 0.9176, 0.9176,  ..., 0.9176, 0.9098, 0.8980],
         [0.9216, 0.9216, 0.9216,  ..., 0.9137, 0.9098, 0.

In [13]:
tensor_img.shape

torch.Size([3, 512, 768])

why Tensor datatype? we have more attribute for trainning and benifit for training

In [14]:
writer.add_image(tag="test_", img_tensor=tensor_img, global_step=1)

different input or output data type
- Tensor
- Opencv
- PIL

normalize()

In [16]:
trans_norm = transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]) # input mean and standard
img_norm = trans_norm(tensor_img) # output[channel] = (input[channel] - mean[channel]) / std[channel] 
img_norm

tensor([[[-0.3725, -0.3725, -0.3725,  ..., -0.3647, -0.3804, -0.4039],
         [-0.3647, -0.3647, -0.3647,  ..., -0.3647, -0.3804, -0.4039],
         [-0.3569, -0.3569, -0.3569,  ..., -0.3725, -0.3804, -0.3961],
         ...,
         [-0.3176, -0.3176, -0.3255,  ..., -0.6549, -0.2549, -0.2941],
         [-0.3176, -0.3176, -0.3255,  ..., -0.3412, -0.2941, -0.3412],
         [-0.3176, -0.3176, -0.3255,  ..., -0.3804, -0.3882, -0.3412]],

        [[ 0.1843,  0.1843,  0.1843,  ...,  0.1922,  0.1765,  0.1529],
         [ 0.1922,  0.1922,  0.1922,  ...,  0.1922,  0.1765,  0.1529],
         [ 0.2000,  0.2000,  0.2000,  ...,  0.1843,  0.1765,  0.1608],
         ...,
         [ 0.2549,  0.2549,  0.2471,  ..., -0.2784,  0.2392,  0.2314],
         [ 0.2549,  0.2549,  0.2471,  ...,  0.1529,  0.2549,  0.1922],
         [ 0.2549,  0.2549,  0.2471,  ...,  0.2549,  0.2471,  0.2627]],

        [[ 0.8275,  0.8275,  0.8275,  ...,  0.8353,  0.8196,  0.7961],
         [ 0.8353,  0.8353,  0.8353,  ...,  0

resize()

In [21]:
# input is PIL image

img.size

(768, 512)

In [22]:
transforms_resize = transforms.Resize((512, 512))
transforms_resize.size

(512, 512)

conpose() more step preporcessing images

In [33]:
transforms_compose = transforms.Compose([transforms.Resize(512), transforms.ToTensor()]) # resize first and then to tensor
transforms_compose

Compose(
    Resize(size=512, interpolation=bilinear, max_size=None, antialias=warn)
    ToTensor()
)

In [32]:
transforms_compose(img)

tensor([[[0.3137, 0.3137, 0.3137,  ..., 0.3176, 0.3098, 0.2980],
         [0.3176, 0.3176, 0.3176,  ..., 0.3176, 0.3098, 0.2980],
         [0.3216, 0.3216, 0.3216,  ..., 0.3137, 0.3098, 0.3020],
         ...,
         [0.3412, 0.3412, 0.3373,  ..., 0.1725, 0.3725, 0.3529],
         [0.3412, 0.3412, 0.3373,  ..., 0.3294, 0.3529, 0.3294],
         [0.3412, 0.3412, 0.3373,  ..., 0.3098, 0.3059, 0.3294]],

        [[0.5922, 0.5922, 0.5922,  ..., 0.5961, 0.5882, 0.5765],
         [0.5961, 0.5961, 0.5961,  ..., 0.5961, 0.5882, 0.5765],
         [0.6000, 0.6000, 0.6000,  ..., 0.5922, 0.5882, 0.5804],
         ...,
         [0.6275, 0.6275, 0.6235,  ..., 0.3608, 0.6196, 0.6157],
         [0.6275, 0.6275, 0.6235,  ..., 0.5765, 0.6275, 0.5961],
         [0.6275, 0.6275, 0.6235,  ..., 0.6275, 0.6235, 0.6314]],

        [[0.9137, 0.9137, 0.9137,  ..., 0.9176, 0.9098, 0.8980],
         [0.9176, 0.9176, 0.9176,  ..., 0.9176, 0.9098, 0.8980],
         [0.9216, 0.9216, 0.9216,  ..., 0.9137, 0.9098, 0.

randomcrop() ... see documentation ctrl click()